mode: Rule
log-level: info

geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo/geoip-all.dat"
  geosite: "https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo/geosite-all.dat"

hosts:
  dns.alidns.com: [223.5.5.5, 223.6.6.6, 2400:3200::1, 2400:3200:baba::1]
  doh.pub: [1.12.12.12, 1.12.12.21, 120.53.53.53]
  dns.google: [8.8.8.8, 8.8.4.4, 2001:4860:4860::8888, 2001:4860:4860::8844]
  cloudflare-dns.com: [1.1.1.1, 1.0.0.1, 2606:4700:4700::1111, 2606:4700:4700::1001]

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  fake-ip-range: 28.0.0.1/8
  enhanced-mode: fake-ip
  fake-ip-filter: ['+.*']
  respect-rules: true
  nameserver:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  direct-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  nameserver-policy:
    '+.gdtel.com': 132.121.218.164
    '+.ctc.com': 132.121.218.164


sniffer:
  enable: true
  sniffing:
    - tls
    - http
    - quic
  force-domain:
    - "*.google.com"
    - "*.formula1.com"
    - "*.telegram.org"
    - "*.telesco.pe" 
    - "*.tdesktop.com"
    - "*.telegra.ph"
    - "*.t.me"
    - "*.jd.com"
  skip-domain:
    - "*.lan"
    - "*.local"
  sniff-tls-ports:
    - 443
    - 8443
  sniff-http-ports:
    - 80
    - 8080
